'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Application
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EasyGest.Application", GetType(Application).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cargando datos, por favor espere..
        '''</summary>
        Friend Shared ReadOnly Property AvisoCargandoDatos() As String
            Get
                Return ResourceManager.GetString("AvisoCargandoDatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La clave introducida no es válido..
        '''</summary>
        Friend Shared ReadOnly Property AvisoClaveIncorrecta() As String
            Get
                Return ResourceManager.GetString("AvisoClaveIncorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor introduce nuevo código de barra..
        '''</summary>
        Friend Shared ReadOnly Property AvisoIntroducirCodigoBarra() As String
            Get
                Return ResourceManager.GetString("AvisoIntroducirCodigoBarra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario no ha sido autentificado, intenta de nuevo..
        '''</summary>
        Friend Shared ReadOnly Property AvisoNoAutentificado() As String
            Get
                Return ResourceManager.GetString("AvisoNoAutentificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ya existe el número de tarjeta, volver a introducir uno..
        '''</summary>
        Friend Shared ReadOnly Property AvisoNumTarjetaDuplicado() As String
            Get
                Return ResourceManager.GetString("AvisoNumTarjetaDuplicado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El test de la conexión de dato ha sido exitosa.  .
        '''</summary>
        Friend Shared ReadOnly Property AvisoProbarConexionExitosa() As String
            Get
                Return ResourceManager.GetString("AvisoProbarConexionExitosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El test de la conexión de dato ha sido fallida..
        '''</summary>
        Friend Shared ReadOnly Property AvisoProbarConexionFallida() As String
            Get
                Return ResourceManager.GetString("AvisoProbarConexionFallida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El proceso se ha cancelado..
        '''</summary>
        Friend Shared ReadOnly Property AvisoProcesoCancelado() As String
            Get
                Return ResourceManager.GetString("AvisoProcesoCancelado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha asignado correctamente el producto a la familia &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property AvisoProductoAsignadoFamilia() As String
            Get
                Return ResourceManager.GetString("AvisoProductoAsignadoFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha asignado correctamente el producto al plan de oferta &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property AvisoProductoAsignadoOferta() As String
            Get
                Return ResourceManager.GetString("AvisoProductoAsignadoOferta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El albaran aún no tiene un cliente asociado, para facturarlo debe seleccionar un cliente..
        '''</summary>
        Friend Shared ReadOnly Property AvisoSeleccionarCliente() As String
            Get
                Return ResourceManager.GetString("AvisoSeleccionarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor seleccione un registro..
        '''</summary>
        Friend Shared ReadOnly Property AvisoSeleccionFila() As String
            Get
                Return ResourceManager.GetString("AvisoSeleccionFila", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En caso de factura o importe debido debe seleccionar un cliente o crearlo de nuevo..
        '''</summary>
        Friend Shared ReadOnly Property AvisoSeleccionObligatoriaCliente() As String
            Get
                Return ResourceManager.GetString("AvisoSeleccionObligatoriaCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Debe seleccionar un proveedor..
        '''</summary>
        Friend Shared ReadOnly Property AvisoSeleccionObligatoriaProveedor() As String
            Get
                Return ResourceManager.GetString("AvisoSeleccionObligatoriaProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor introduce el descuento..
        '''</summary>
        Friend Shared ReadOnly Property AvisoSolicitarDescuento() As String
            Get
                Return ResourceManager.GetString("AvisoSolicitarDescuento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El vale de compra no es válido..
        '''</summary>
        Friend Shared ReadOnly Property AvisoValeNoValido() As String
            Get
                Return ResourceManager.GetString("AvisoValeNoValido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El vale de compra está caducado, pero de toda la manera desea acptarlo?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionAceptarValeCaducado() As String
            Get
                Return ResourceManager.GetString("ConfirmacionAceptarValeCaducado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha modificado la condición de la tarjeta de fidelización, qué desea hacer con esta modificación? 
        '''Sí, modificar todas las tarjetas.
        '''No, modificar solamente aquellas tarjetas que no poseen una condión particular.
        '''Cancelar, deshacer los cambios en condiciones de la tarjeta de fidelización..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionActualizarCondicionTarjeta() As String
            Get
                Return ResourceManager.GetString("ConfirmacionActualizarCondicionTarjeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirma la eliminación del registro?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionBorrarDato() As String
            Get
                Return ResourceManager.GetString("ConfirmacionBorrarDato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirme la cancelación del vale seleccionado
        '''Nº: {0} Importe: {1}.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionCancelarVale() As String
            Get
                Return ResourceManager.GetString("ConfirmacionCancelarVale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ante de abandonar la aplicación desea cerrar curso actual de la caja?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionCerrarCaja() As String
            Get
                Return ResourceManager.GetString("ConfirmacionCerrarCaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El curso de la caja en el {0} aún no se ha cerrado, desea mantenerlo? Si confirma, entonces se calculará conjuntamente en el proximo cierre..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionCerrarCajaAnterior() As String
            Get
                Return ResourceManager.GetString("ConfirmacionCerrarCajaAnterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aún no existe un producto con la referencia coincidente a la de introducida, desea crear uno nuevo?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionCrearProducto() As String
            Get
                Return ResourceManager.GetString("ConfirmacionCrearProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desea devolver importe en metalico?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionDevolucionMetalica() As String
            Get
                Return ResourceManager.GetString("ConfirmacionDevolucionMetalica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En esta compra el cliente utilizó un vale como medio de pago, pero queda cambio para cliente, desea emitir un nuevo vale con el importe de cambio?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionEmitirVale() As String
            Get
                Return ResourceManager.GetString("ConfirmacionEmitirVale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error no controlado en la ejecución, por favor consulte los archivos de log. ¿Deseas continuar la ejecución?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionErrorNoControlado() As String
            Get
                Return ResourceManager.GetString("ConfirmacionErrorNoControlado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Necesita guardar albarán actual?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionGuardarAlbaran() As String
            Get
                Return ResourceManager.GetString("ConfirmacionGuardarAlbaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Necesita guardar pedido actual?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionGuardarPedido() As String
            Get
                Return ResourceManager.GetString("ConfirmacionGuardarPedido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desea imprimir el albarán?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionImprimirAlbaran() As String
            Get
                Return ResourceManager.GetString("ConfirmacionImprimirAlbaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirme la reactivación del vale seleccionado
        '''Nº: {0} Importe: {1}.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionReactivarVale() As String
            Get
                Return ResourceManager.GetString("ConfirmacionReactivarVale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La referencia ya existe en la base de dato, desea continuar y crear un producto nuevo con esta referencia?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionReferenciaDuplicada() As String
            Get
                Return ResourceManager.GetString("ConfirmacionReferenciaDuplicada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desea abandonar la aplicación?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmacionSalir() As String
            Get
                Return ResourceManager.GetString("ConfirmacionSalir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingreso a caja, 〔{0}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoCobroAlbaran() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoCobroAlbaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cobro del credito de cliente, 〔{0} ： {1}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoCobroCredito() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoCobroCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Devolución metalico de proveedor, 〔{0}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoCobroPedidoDev() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoCobroPedidoDev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Devolución metalico a cliente, 〔{0}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoPagoAlbaranDev() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoPagoAlbaranDev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pago del debito a proveedor,〔{0} ： {1}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoPagoDebito() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoPagoDebito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salida de caja, 〔{0}〕.
        '''</summary>
        Friend Shared ReadOnly Property DescripcionConceptoPagoPedido() As String
            Get
                Return ResourceManager.GetString("DescripcionConceptoPagoPedido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Emitido manualmente por {0}. .
        '''</summary>
        Friend Shared ReadOnly Property DescripcionMovTarjEmisionManual() As String
            Get
                Return ResourceManager.GetString("DescripcionMovTarjEmisionManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en la actualización de los datos..
        '''</summary>
        Friend Shared ReadOnly Property ErrorActualizarDatos() As String
            Get
                Return ResourceManager.GetString("ErrorActualizarDatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en el ajuste de los albaranes..
        '''</summary>
        Friend Shared ReadOnly Property ErrorAjusteAlbaran() As String
            Get
                Return ResourceManager.GetString("ErrorAjusteAlbaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en la ejecución, por favor consulte los archivos de log..
        '''</summary>
        Friend Shared ReadOnly Property ErrorAplicacion() As String
            Get
                Return ResourceManager.GetString("ErrorAplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en el calculo de la recaudación..
        '''</summary>
        Friend Shared ReadOnly Property ErrorCalcularRecaudacion() As String
            Get
                Return ResourceManager.GetString("ErrorCalcularRecaudacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en la carga de los datos..
        '''</summary>
        Friend Shared ReadOnly Property ErrorCargarDatos() As String
            Get
                Return ResourceManager.GetString("ErrorCargarDatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en la carga de los informes..
        '''</summary>
        Friend Shared ReadOnly Property ErrorCargarInforme() As String
            Get
                Return ResourceManager.GetString("ErrorCargarInforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en la facturación de los albaranes..
        '''</summary>
        Friend Shared ReadOnly Property ErrorFacturarAlbaran() As String
            Get
                Return ResourceManager.GetString("ErrorFacturarAlbaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No es posible imprimir..
        '''</summary>
        Friend Shared ReadOnly Property ErrorNoImprimir() As String
            Get
                Return ResourceManager.GetString("ErrorNoImprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error en el proceso de importación/exportación..
        '''</summary>
        Friend Shared ReadOnly Property ErrorProcesoImpExp() As String
            Get
                Return ResourceManager.GetString("ErrorProcesoImpExp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº cliente;Nombre;Tipo ident.;Nº ident.;Dirección;CP;Localidad;Provincia;F. creación.
        '''</summary>
        Friend Shared ReadOnly Property GridHeaderTextBuscarCliente() As String
            Get
                Return ResourceManager.GetString("GridHeaderTextBuscarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Referencia;Producto;P. venta;Ult. proveedor;Familia;Ubicación;Marca;F. creación.
        '''</summary>
        Friend Shared ReadOnly Property GridHeaderTextBuscarProducto() As String
            Get
                Return ResourceManager.GetString("GridHeaderTextBuscarProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº proveedor;Nombre;Nombre CN;Tipo ident.;Nº ident.;Dirección;CP;Localidad;Provincia;F. creación.
        '''</summary>
        Friend Shared ReadOnly Property GridHeaderTextBuscarProveedor() As String
            Get
                Return ResourceManager.GetString("GridHeaderTextBuscarProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Producto;Referencia;Observación;F.Creación;Encargo.
        '''</summary>
        Friend Shared ReadOnly Property GridHeaderTextListaInicio() As String
            Get
                Return ResourceManager.GetString("GridHeaderTextListaInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ;Tarea;Fecha;Hora.
        '''</summary>
        Friend Shared ReadOnly Property GridHeaderTextTareaInicio() As String
            Get
                Return ResourceManager.GetString("GridHeaderTextTareaInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esperando la autentificación de usuario..
        '''</summary>
        Friend Shared ReadOnly Property InfoAccionEsperarAutentificacion() As String
            Get
                Return ResourceManager.GetString("InfoAccionEsperarAutentificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Preparando formulario principal..
        '''</summary>
        Friend Shared ReadOnly Property InfoAccionPrepararPrincipal() As String
            Get
                Return ResourceManager.GetString("InfoAccionPrepararPrincipal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Comprobar la conexión..
        '''</summary>
        Friend Shared ReadOnly Property InfoAccionProbarConexion() As String
            Get
                Return ResourceManager.GetString("InfoAccionProbarConexion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enero;Febrero;Marzo;Abril;Mayo;Junio;Julio;Agosto;Septiembre;Octubre;Noviembre;Diciembre.
        '''</summary>
        Friend Shared ReadOnly Property Meses() As String
            Get
                Return ResourceManager.GetString("Meses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diario;1ª Semana(1-7);2ª Semana(8-14);3ª Semana(15-21);4ª Semana(22-?);Mensual;Bimestral;Trimestral;Semestral;Anual.
        '''</summary>
        Friend Shared ReadOnly Property Periodos() As String
            Get
                Return ResourceManager.GetString("Periodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Normal;Reducido;Superreducido.
        '''</summary>
        Friend Shared ReadOnly Property Tarifas() As String
            Get
                Return ResourceManager.GetString("Tarifas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activar.
        '''</summary>
        Friend Shared ReadOnly Property TextoActivar() As String
            Get
                Return ResourceManager.GetString("TextoActivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activos.
        '''</summary>
        Friend Shared ReadOnly Property TextoActivo() As String
            Get
                Return ResourceManager.GetString("TextoActivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buscar.
        '''</summary>
        Friend Shared ReadOnly Property TextoBuscar() As String
            Get
                Return ResourceManager.GetString("TextoBuscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Campos.
        '''</summary>
        Friend Shared ReadOnly Property TextoCampos() As String
            Get
                Return ResourceManager.GetString("TextoCampos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cliente.
        '''</summary>
        Friend Shared ReadOnly Property TextoCliente() As String
            Get
                Return ResourceManager.GetString("TextoCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Código.
        '''</summary>
        Friend Shared ReadOnly Property TextoCodigo() As String
            Get
                Return ResourceManager.GetString("TextoCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contiene.
        '''</summary>
        Friend Shared ReadOnly Property TextoContiene() As String
            Get
                Return ResourceManager.GetString("TextoContiene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desactivar.
        '''</summary>
        Friend Shared ReadOnly Property TextoDesactivar() As String
            Get
                Return ResourceManager.GetString("TextoDesactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Categorizar {0} en familia {1}..
        '''</summary>
        Friend Shared ReadOnly Property TextoDescCategorizarProducto() As String
            Get
                Return ResourceManager.GetString("TextoDescCategorizarProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Establecer {0} en oferta nº {1}..
        '''</summary>
        Friend Shared ReadOnly Property TextoDescEstablecerOfertaProducto() As String
            Get
                Return ResourceManager.GetString("TextoDescEstablecerOfertaProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Procesado {0} registro/s en {1} ms..
        '''</summary>
        Friend Shared ReadOnly Property TextoDiagnosticoConsulta() As String
            Get
                Return ResourceManager.GetString("TextoDiagnosticoConsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Distinto.
        '''</summary>
        Friend Shared ReadOnly Property TextoDistinto() As String
            Get
                Return ResourceManager.GetString("TextoDistinto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empieza Por.
        '''</summary>
        Friend Shared ReadOnly Property TextoEmpiezaPor() As String
            Get
                Return ResourceManager.GetString("TextoEmpiezaPor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empresa.
        '''</summary>
        Friend Shared ReadOnly Property TextoEmpresa() As String
            Get
                Return ResourceManager.GetString("TextoEmpresa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es Nulo.
        '''</summary>
        Friend Shared ReadOnly Property TextoEsNulo() As String
            Get
                Return ResourceManager.GetString("TextoEsNulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha creación.
        '''</summary>
        Friend Shared ReadOnly Property TextoFechaCreacion() As String
            Get
                Return ResourceManager.GetString("TextoFechaCreacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha modificación.
        '''</summary>
        Friend Shared ReadOnly Property TextoFechaModificacion() As String
            Get
                Return ResourceManager.GetString("TextoFechaModificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cliente {0} posee {1} tarjeta/s activo/s con el saldo actual de {2}..
        '''</summary>
        Friend Shared ReadOnly Property TextoGrupoTarjetaFidelidelizacion() As String
            Get
                Return ResourceManager.GetString("TextoGrupoTarjetaFidelidelizacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hora Apertura Caja.
        '''</summary>
        Friend Shared ReadOnly Property TextoHoraApertura() As String
            Get
                Return ResourceManager.GetString("TextoHoraApertura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hora Inicio Aplicación.
        '''</summary>
        Friend Shared ReadOnly Property TextoHoraInicio() As String
            Get
                Return ResourceManager.GetString("TextoHoraInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identificación.
        '''</summary>
        Friend Shared ReadOnly Property TextoIdentificacion() As String
            Get
                Return ResourceManager.GetString("TextoIdentificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Igual.
        '''</summary>
        Friend Shared ReadOnly Property TextoIgual() As String
            Get
                Return ResourceManager.GetString("TextoIgual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mayor.
        '''</summary>
        Friend Shared ReadOnly Property TextoMayor() As String
            Get
                Return ResourceManager.GetString("TextoMayor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mayor o Igual.
        '''</summary>
        Friend Shared ReadOnly Property TextoMayorIgual() As String
            Get
                Return ResourceManager.GetString("TextoMayorIgual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Menor.
        '''</summary>
        Friend Shared ReadOnly Property TextoMenor() As String
            Get
                Return ResourceManager.GetString("TextoMenor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Menor o Igual.
        '''</summary>
        Friend Shared ReadOnly Property TextoMenorIgual() As String
            Get
                Return ResourceManager.GetString("TextoMenorIgual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inactivos.
        '''</summary>
        Friend Shared ReadOnly Property TextoNoActivo() As String
            Get
                Return ResourceManager.GetString("TextoNoActivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No Contiene.
        '''</summary>
        Friend Shared ReadOnly Property TextoNoContiene() As String
            Get
                Return ResourceManager.GetString("TextoNoContiene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property TextoNombre() As String
            Get
                Return ResourceManager.GetString("TextoNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No Nulo.
        '''</summary>
        Friend Shared ReadOnly Property TextoNoNulo() As String
            Get
                Return ResourceManager.GetString("TextoNoNulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº Oferta.
        '''</summary>
        Friend Shared ReadOnly Property TextoNumeroOferta() As String
            Get
                Return ResourceManager.GetString("TextoNumeroOferta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Operadores.
        '''</summary>
        Friend Shared ReadOnly Property TextoOperadores() As String
            Get
                Return ResourceManager.GetString("TextoOperadores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Orden.
        '''</summary>
        Friend Shared ReadOnly Property TextoOrden() As String
            Get
                Return ResourceManager.GetString("TextoOrden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ascendente.
        '''</summary>
        Friend Shared ReadOnly Property TextoOrdenAsc() As String
            Get
                Return ResourceManager.GetString("TextoOrdenAsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descendente.
        '''</summary>
        Friend Shared ReadOnly Property TextoOrdenDesc() As String
            Get
                Return ResourceManager.GetString("TextoOrdenDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Plan.
        '''</summary>
        Friend Shared ReadOnly Property TextoPlan() As String
            Get
                Return ResourceManager.GetString("TextoPlan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Producto.
        '''</summary>
        Friend Shared ReadOnly Property TextoProducto() As String
            Get
                Return ResourceManager.GetString("TextoProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Productos no categorizados.
        '''</summary>
        Friend Shared ReadOnly Property TextoProductoNoCategorizado() As String
            Get
                Return ResourceManager.GetString("TextoProductoNoCategorizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Productos no ofertados.
        '''</summary>
        Friend Shared ReadOnly Property TextoProductoNoOfertado() As String
            Get
                Return ResourceManager.GetString("TextoProductoNoOfertado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Proveedor.
        '''</summary>
        Friend Shared ReadOnly Property TextoProveedor() As String
            Get
                Return ResourceManager.GetString("TextoProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Puesto.
        '''</summary>
        Friend Shared ReadOnly Property TextoPuesto() As String
            Get
                Return ResourceManager.GetString("TextoPuesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recargar.
        '''</summary>
        Friend Shared ReadOnly Property TextoRecargar() As String
            Get
                Return ResourceManager.GetString("TextoRecargar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Termina En.
        '''</summary>
        Friend Shared ReadOnly Property TextoTerminaEn() As String
            Get
                Return ResourceManager.GetString("TextoTerminaEn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario.
        '''</summary>
        Friend Shared ReadOnly Property TextoUsuario() As String
            Get
                Return ResourceManager.GetString("TextoUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Valor.
        '''</summary>
        Friend Shared ReadOnly Property TextoValor() As String
            Get
                Return ResourceManager.GetString("TextoValor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Valor duplicado.
        '''</summary>
        Friend Shared ReadOnly Property TextoValorDuplicado() As String
            Get
                Return ResourceManager.GetString("TextoValorDuplicado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Valor requerido.
        '''</summary>
        Friend Shared ReadOnly Property TextoValorRequerido() As String
            Get
                Return ResourceManager.GetString("TextoValorRequerido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Versión.
        '''</summary>
        Friend Shared ReadOnly Property TextoVersion() As String
            Get
                Return ResourceManager.GetString("TextoVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error Aplicación.
        '''</summary>
        Friend Shared ReadOnly Property TituloErrorAplicativo() As String
            Get
                Return ResourceManager.GetString("TituloErrorAplicativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Compra mensual.
        '''</summary>
        Friend Shared ReadOnly Property TituloGraficoCompraMensual() As String
            Get
                Return ResourceManager.GetString("TituloGraficoCompraMensual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diferencia Venta - Compra.
        '''</summary>
        Friend Shared ReadOnly Property TituloGraficoCompraVenta() As String
            Get
                Return ResourceManager.GetString("TituloGraficoCompraVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Venta mensual.
        '''</summary>
        Friend Shared ReadOnly Property TituloGraficoVentaMensual() As String
            Get
                Return ResourceManager.GetString("TituloGraficoVentaMensual", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
